### ISSUE TITLE
在项目中使用最新版本item不充满一屏时还是有个多余的foot

### ISSUE THREAD

**Issue by 7449** [XRecyclerView/XRecyclerView#103]

**Comment by gao746700783** [comment]
是的，仍然存在啊，感觉跟个尾巴似的

**Comment by 7449** [comment]
只要项目不要求ios风格，用SwipeRefreshLayout 以及自己封装个BaseRecyclerViewAdapter吧 ，比较简单

**Comment by jwfsky** [comment]
加载完成后，footerview的Visibility属性被设置成gone。但是WrapAdapter依然将footerview作为item添加进去，也不知道为什么recyerview依然计算出了Visibility属性设置为gone的item的高度。这就造成了footer一直占据空间的情况。解决办法是重写wrapadapter中的getFootercount方法：
`` public int getFootersCount() {
                int tempCount=0;
                for(View view:mFootViews){
                    if(view.getVisibility()!=GONE){
                        tempCount++;
                    }
                }
                return tempCount;
            }

这个改了之后，解决了问题。可是滚动时候出现卡顿。 @jianghejie 大神有空帮忙看一下

**Comment by JustinRoom** [comment]
https://github.com/JustinRoom/XRecyclerViewLayout下载这个model，可以根据你的需求稍做修改

**Comment by 7449** [comment]
@JustinRoom  这个问题很早以前就搞好了
