### ISSUE TITLE
Adapter 中notifyItemRemoved()报错

### ISSUE THREAD

**Issue by wujuan** [XRecyclerView/XRecyclerView#108]
删除列表中的首末条目时：java.lang.IllegalArgumentException: Called attach on a child which is not detached ViewHolder{41cede38 position=7 id=-1, oldPos=-1, pLpos:-1}
烦解

**Comment by wuruize** [comment]
我也是

**Comment by initzf** [comment]
@wuruize  @wujuan   我做删除的时候也遇上这个问题了，你们怎么解决的啊。

**Comment by ldqmaybe** [comment]
我做删除的时候也遇上这个问题了，你们怎么解决的啊。

**Comment by jiawei-i** [comment]
是不是增加了headerview 减掉headerview个数和刷新的那个个数。如果没有加headerview就减掉刷新的布局个数也就是减掉1。

**Comment by ldqmaybe** [comment]
@jiawei-i 这样做是没错，但是好像使用notifyItemRemoved(position)不起列表刷新作用，不知道你的会不会这样？如果使用notifyDataSetChanged()又没有动画效果。

**Comment by af913337456** [comment]
已修复，见最近的 commit ，2017-11-14
