### ISSUE TITLE
setRefreshProgressStyle有内存泄露

### ISSUE THREAD

**Issue by swepthong** [XRecyclerView/XRecyclerView#132]
如图所示

![screenshot_2016-09-27-11-14-38_com shuxun autoformedia](https://cloud.githubusercontent.com/assets/8691972/18859192/7435866e-84a4-11e6-8be1-4ccc3d036bfa.png)

![screenshot_2016-09-27-11-14-27_com shuxun autoformedia](https://cloud.githubusercontent.com/assets/8691972/18859189/6b8da5be-84a4-11e6-8be4-c0390d13bffb.png)

**Comment by tianHouChao** [comment]
是的，内存泄漏啊。解决了么？

**Comment by af913337456** [comment]
见 1.5.5 版本，已经修复
