### ISSUE TITLE
CoordinatorLayout嵌套XRecyclerView

### ISSUE THREAD

**Issue by LuoDiKaiHua** [XRecyclerView/XRecyclerView#166]
当CoordinatorLayout嵌套XRecyclerView的时候事先不触摸XRecyclerView的话触摸AppBarLayout部分是能进行滑动的, 一旦点击或者触摸了XRecyclerView之后AppBarLayout就再也不能触摸滑动了

**Comment by jianghejie** [comment]
为什么我没遇到这种情况呢？

**Comment by zhangweicheng2013** [comment]
我也遇到这个问题了

**Comment by keshuangjie** [comment]
同样遇到这个问题，AppBarLayout触摸事件感觉被XRecyclerView吃掉了

**Comment by zhangweicheng2013** [comment]
自己自定义一个implements NestedScrollingChild 的ViewGroup,然后把这个ViewGroup加在AppBarLayout与AppBarLayout的子view的中间。自定义ViewGroup 可以参考下RecyclerView的implements NestedScrollingChild 相关逻辑

**Comment by fengfutong** [comment]
这个问题还是存在，Demo中的第六个，CollapsingToolbarLayoutTest中，当我们进入这个页面，不触摸recyclerview，而是首先摁住头图进行滑动的时候，recyclerview是可以随着一起滑动的。但是一旦触摸了recyclerview，那么摁住头图进行滑动就无效了。

**Comment by qingfengnongtang** [comment]
有解决办法吗
