### ISSUE TITLE
删除item时position的问题

### ISSUE THREAD

**Issue by ldqmaybe** [XRecyclerView/XRecyclerView#198]
点击删除item时，调用 notifyItemRemoved(holder.getAdapterPosition())方法，完全是乱的（添加了个headerView）

**Comment by Longalei** [comment]
对啊。这个是乱的，所以你刷新的时候可能需要position减掉头布局以及刷新布局的个数。这其中乱的原因就是在于headerView的添加根本原理就在于headerview也是Recyclerview的一种Type。只是作者给我们封装好了而已。其实我认为做这种刷新与加载如果需要更好的使用recyclerview那么就可以自己写一个View容器将头布局以及recyclerview以及尾布局都当作其中的一部分。

**Comment by ldqmaybe** [comment]
确实是需要减去头部布局个数和刷新布局个数，但是如果是删除item的话调用notifyItemRemoved(position)并不起作用，需要调用 notifyDataSetChanged()才行，代价是没有删除动画。有没有更好的解决方案？

**Comment by jiawei-i** [comment]
notifyItemRangeChanged(你的布局个数, getItemCount());

**Comment by ldqmaybe** [comment]
java.lang.IllegalArgumentException: Called attach on a child which is not detached: ViewHolder{1bd49c96 position=14 id=-1, oldPos=-1, pLpos:-1}
只要 “上拉加载更多”  ，点击最后一个item就出现，onLoadMore()里面并没有做任何操作，是不是在触发这个方法的时候position又发生了什么变化

**Comment by jiawei-i** [comment]
你点击的传进去的position不对，你debug一下。

**Comment by ldqmaybe** [comment]
1、没有header；
2、我的datas.size()=15；
3、删除的是item14，传进去的position是14；
4、执行删除的代码是
datas.remove(position)；
notifyItemRemoved(position+1);
notifyItemRangeChanged(position+1,getItemCount());

**Comment by 13273026553** [comment]
public void remove(int position) {
        mStrings.remove(position);
//        notifyItemRemoved(position);
//        notifyItemRangeChanged(position,mStrings.size()-position);
        notifyItemRemoved(position+1);
        notifyItemRangeChanged(position+1,mStrings.size()-position);
    }

**Comment by 13273026553** [comment]
解决了

**Comment by af913337456** [comment]
已修复，见最近的更新，2017-11-14
