### ISSUE TITLE
加载更多触发条件

### ISSUE THREAD

**Issue by yhsj0919** [XRecyclerView/XRecyclerView#2]
希望改为数据必须多于一屏在进行加载，不足一屏的时候屏蔽加载更多

**Comment by jianghejie** [comment]
恩，这个问题我已经发现了，还没来得及完善，谢谢反馈

**Comment by jianghejie** [comment]
不足一屏的时候已经屏蔽了加载更多

**Comment by jianghejie** [comment]
已经修改

**Comment by sun-sky** [comment]
不足一屏的时候应该继续执行加载更多，当加载更多方法没有加载新的数据的话，关闭加载更多方法。如果不足一屏，会一直加载更多，直到满屏或者无数据才不会调用更加方法。

**Comment by blankfu** [comment]
楼上说的有道理
