### ISSUE TITLE
多次调用setAdapter崩溃

### ISSUE THREAD

**Issue by dakun666** [XRecyclerView/XRecyclerView#212]
两次及以上次数调用setAdapter，出现
`Observer com.jcodecraeer.xrecyclerview.XRecyclerView$DataObserver@25e113a2 is already registered.`
的错误。

**Comment by jdsjlzx** [comment]
不要多次调用setAdapter方法，调用一次就可以了，下次调用notifyDataSetChanged();即可。
你也可以看看这个框架的实现：https://github.com/jdsjlzx/LRecyclerView

**Comment by dakun666** [comment]
谢谢，已经解决了。我并不是更新数据时调用的setAdapter，而是有两套数据、两套布局，所以写的两个adapter，切换数据时报的这个错。我的解决方式是使用了类似google的SwipeRefreshLayout方法解决的。这种包裹的做法让我不必改动太多原始的代码...在原生RecyclerView中并不会有多次调用setAdapter引发bug的现象，所以我认为库中setAdapter的逻辑应该是有些许问题。再次感谢🙏🙏🙏
