### ISSUE TITLE
如何移除headerview

### ISSUE THREAD

**Issue by davidhhuan** [XRecyclerView/XRecyclerView#241]
当前版本只有addHeaderView方法，没有removeHeaderView方法。本来想写一个

最简单的方式
```
public void removeHeaderView(View view) {
        if (mHeaderViews.contains(view)) {
            view.setVisibility(GONE);
        }
    }
```
的确是可以隐藏了，但留下了一片空白
![image](https://cloud.githubusercontent.com/assets/449399/25389402/13a08a9c-2a03-11e7-9e17-131dde496302.png)

方案二
```
    public void removeHeaderView(View view) {
        if (mHeaderViews.contains(view)) {
//            int position = mHeaderViews.indexOf(view);
//            sHeaderTypes.remove(position);
            mHeaderViews.remove(view);

            if (mWrapAdapter != null) {
                mWrapAdapter.notifyDataSetChanged();
                getLayoutManager().scrollToPosition(0);
            }
        }
    }
```
会报错，请问有什么方法可以removeHeaderView的？

**Comment by mercuryglory** [comment]
`public void removeHeaderView() {
        if (mWrapAdapter.getHeadersCount() > 0) {
            View headerView = getHeaderView();
            mHeaderViews.remove(headerView);
            mWrapAdapter.notifyDataSetChanged();
        }
    }

    public View getHeaderView() {
        return mWrapAdapter.getHeadersCount() > 0 ? mHeaderViews.get(0) : null;
    }`

**Comment by af913337456** [comment]
代码已提供方法
