### ISSUE TITLE
刷新数据问题

### ISSUE THREAD

**Issue by kanshenmekan** [XRecyclerView/XRecyclerView#250]
只能用这个mAdapter.notifyDataSetChanged();
notifyItemChanged(position);或者 mAdapter.notifyItemRangeChanged(0,mDatas.size());就会报错，
信息： java.lang.IllegalArgumentException: Called attach on a child which is not detached: ViewHolder{62299ab position=1 id=-1, oldPos=-1, pLpos:-1}

当时当你上下活动之后，再执行notifyItemChanged(position);又不报错了。

**Comment by af913337456** [comment]
@kanshenmekan  已修复，2017-11-14
