### ISSUE TITLE
footer不显示

### ISSUE THREAD

**Issue by AmoyJJ** [XRecyclerView/XRecyclerView#277]
添加footer不会显示 与loadmorecompter相冲突！！！

**Comment by fangxiaogang** [comment]
我也发现了。作者还在维护吗

**Comment by AmoyJJ** [comment]
应该是没维护了吧。上次更新6个月前了。可以换https://github.com/CymChad/BaseRecyclerViewAdapterHelper
之前项目用过。还不错。XRecyclerView也不错

**Comment by ZZombiee** [comment]
添加一个int变量footIndex，修改onCreateViewHolder方法中
 else if (viewType == TYPE_FOOTER) {
                return new SuperRecycleView.WrapAdapter.SimpleViewHolder(mFootViews.get(0));
            }
为
 else if (viewType == TYPE_FOOTER) {
                return new SuperRecycleView.WrapAdapter.SimpleViewHolder(mFootViews.get(footIndex++));
            }
即可，或者在addFoot方法中直接mFootViews.clear()后再添加foot，只是这样的话就不能上拉了

**Comment by af913337456** [comment]
已经更新 @AmoyJJ

**Comment by af913337456** [comment]
@fangxiaogang  见 1.5.2 已经提供
