### ISSUE TITLE
Sometime LoadMore not call when Scrolling

### ISSUE THREAD

**Issue by ashishCDN0135** [XRecyclerView/XRecyclerView#278]
hii i am facing issue where when i want load more data and scroll it doesnt work and the same time when i define padding in xRecylerview xml it work properly..

**Comment by af913337456** [comment]
the item of data is not enough,try to show more items in one page,then scroll

**Comment by fukemy** [comment]
@af913337456 hi, when in android phone loadmore work normally, but in tablet the datas not fill the recyclerview height, so can not loadmore, can u help?
