### ISSUE TITLE
数据条目未到底触发加载

### ISSUE THREAD

**Issue by duyb** [XRecyclerView/XRecyclerView#283]
在滑动过程中，还未滑到已经显示数据数据条目底部时，只要一松手也会触发加载（mLoadingListener.onLoadMore()），导致频繁调用加载更多业务方法。

**Comment by TYUpya** [comment]
Is there any solution to this problem?请问这个问题有被解决吗？

**Comment by fukemy** [comment]
still not solved. on load more take 5 second after scroll to end to show
