### ISSUE TITLE
刷新动画的View会长期持有对应Activity的context导致OOM

### ISSUE THREAD

**Issue by qq516633632** [XRecyclerView/XRecyclerView#284]
由于刷新动画中例如:  
scaleAnim.addUpdateListener(new ValueAnimator.AnimatorUpdateListener() {
                @Override
                public void onAnimationUpdate(ValueAnimator animation) {
                    scaleFloats[index] = (float) animation.getAnimatedValue();
                    postInvalidate();
                }
            });
在这段代码中由于监听的内部类持有了外部类的VIew 而View有Activity创建 导致CG无法回收 从而引发内存泄漏 注释掉动画的部分 CG会正常回收

**Comment by 805447391** [comment]
用弱引用试试。

**Comment by af913337456** [comment]
见 1.5.5 版本，已经修复
