### ISSUE TITLE
初始化添加了 一个头 但是刷新的时候 头数据为空 怎么删掉头呢

### ISSUE THREAD

**Issue by lrain-lv** [XRecyclerView/XRecyclerView#289]
初始化添加了 一个头 但是刷新的时候 头数据为空 怎么删掉头呢

**Comment by ZZombiee** [comment]
需要改造一下里面的方法，如
   public void removeHead(View v) {
        for (View view : mHeaderViews) {
            if (view == v)
                mHeaderViews.remove(view);
        }
    }

**Comment by af913337456** [comment]
已添加 remove
