### ISSUE TITLE
用三星手机滑动列表的时候，随机的奔溃

### ISSUE THREAD

**Issue by diasstant-ht** [XRecyclerView/XRecyclerView#291]

**Comment by linqssonny** [comment]
有解决方案吗？  一行三列，  会崩溃

**Comment by Random-ht** [comment]
没有  我直接换的别的控件

**Comment by linqssonny** [comment]
换成别的什么控件？分享一下，我也去看看

**Comment by Random-ht** [comment]
SmartRefreshLayout 我只用上了他的下拉刷新和上拉加载更多   看你的项目有什么需求咯

**Comment by linqssonny** [comment]
thank  you

**Comment by linqssonny** [comment]
这个可能跟系统有关系，我把XRecyclerView所在的Activity硬件加速关掉，目前崩溃没出现，android:hardwareAccelerated="false"。
