### ISSUE TITLE
How to get viewHolder object?

### ISSUE THREAD

**Issue by arpitjoshi08** [XRecyclerView/XRecyclerView#292]
Using  recyclerview we can get object of view holder like  `    ViewHolder holder = (ViewHolder) recyclerView.findViewHolderForAdapterPosition(selectedItem);`
but using this XRecyclerView we are getting null view holder how can i get view using this ?

**Comment by af913337456** [comment]
clone this project,import the library and extend this function by yourself,it wont be hard
