### ISSUE TITLE
数据少时不走onLoadMore方法，每次返回三条数据,加载就不走这个方法?

### ISSUE THREAD

**Issue by wdza** [XRecyclerView/XRecyclerView#294]
数据少时不走onLoadMore方法，每次返回三条数据,加载就不走这个方法?

**Comment by shallowlight** [comment]
准确的讲是：当设置一页的数据少于或者等于一屏所能容纳的数据时，监听到滑动以后，xRecyclerview 的onScrollStateChanged，第一个判断语句`if (state == RecyclerView.SCROLL_STATE_IDLE && mLoadingListener != null && !isLoadingData && loadingMoreEnabled)`，里面的state != RecyclerView.SCROLL_STATE_IDLE ，导致无法执行到加载更多的监听
