### ISSUE TITLE
support升级后问题

### ISSUE THREAD

**Issue by daiwenbo88** [XRecyclerView/XRecyclerView#295]
升级到com.android.support:appcompat-v7:25.3.1 后就有问题

**Comment by Jenus** [comment]
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:23.4.0' 
    compile 'com.android.support:recyclerview-v7:23.4.0'
    compile 'com.android.support:design:23.4.0'
}


Please replaced using placeholder like v7:${DEPENDENCY_SUPPORT_LIBRARY_VERSION}  if compatible. Then the App can using latest version support without conflict with different version.
