### ISSUE TITLE
Not scrolling till the last position

### ISSUE THREAD

**Issue by arpitjoshi08** [XRecyclerView/XRecyclerView#297]
i am using this and working fine but getting one issue is that i want to scroll recyclerview so i am using this 
`recyclerview.scrollToPosition(vendorList.size() - 1)` but getting issue is that list not scrolling till last item. Only scrolling with second last item and last item always hidden, how can i resolved that?

**Comment by af913337456** [comment]
last item should be the footer view,child of the recyclerview,you wanna to scroll to the bottom,the real position is the list.size - 2
