### ISSUE TITLE
横向布局出现第一页空白

### ISSUE THREAD

**Issue by SpringSmell** [XRecyclerView/XRecyclerView#298]
new LinearLayoutManager(this, LinearLayoutManager.HORIZONTAL, false)
不管Item如何设置，都会出现第一页空白，是头部问题？

1、下拉刷新与上拉加载都关闭了
2、并未设置header或者布局margin、padding。

原生的RecyclerView正常

**Comment by af913337456** [comment]
getDefaultHeaderVIew . set gone , 看最近提交记录

**Comment by suchengjian** [comment]
设置了还是没有用
