### ISSUE TITLE
设置长按监听时的BUG

### ISSUE THREAD

**Issue by geekqian** [XRecyclerView/XRecyclerView#308]
XRecyclerView 在监听长按时, 获取到的 position 因为加了下拉刷新头的关系, 所以会自动 +1 . 但是在该方法中调用 `notifyItemChanged(position);` 触发到 `onBindViewHolder` 中获取的 position 却没有自动 +1 . 导致了刷新时刷新的位置不对应的问题. 
目前我的解决方案是额外加了一个缺省值, 默认值为 0 , 当触发长按或点击时 缺省值赋值为 1. 
最终在 `onBindViewHolder` 中把 position += 缺省值; 
解决这个问题, 但是不知道是什么原因导致的这个BUG. 

------------
更新:  这种解决方案又导致了在滑动时产生越界异常的 bug 

----------
再次更新:  查到是下面 XRecyclerView.java 中的这句代码做了减法, 但不知道作者的用意是什么

![image](https://user-images.githubusercontent.com/15983385/33207837-30022d5a-d14a-11e7-84b4-ad474492376e.png)

**Comment by af913337456** [comment]
@geekqian  使用最新代码中的，notifyItemRemoved 方法。红框代码已经很明显告诉你，减去的是自定义头部的size，意义就是得出真实的 pos 对应 list 的位置
