### ISSUE TITLE
7.0上demo显示异常

### ISSUE THREAD

**Issue by yungelee** [XRecyclerView/XRecyclerView#311]
只是在跑了下demo, 发现好几个demo界面在7.0上标题栏和状态栏位置重叠了,并且标题栏和下面一部分是白色空白 这样和下面的显示空间中出现了一大块白条.

**Comment by af913337456** [comment]
这是 actionBar 适配问题，demo 的是手动设置的，这个和 XR 无关，具体的 bar 效果自己加到自己的页面

**Comment by yungelee** [comment]
ok啊，是和XR无关，但是demo看起来很不舒服啊。那你在哪个api上没有适配问题(6.0也同7.0是一样)，我然后试着改下。
