### ISSUE TITLE
vivo x20 不能加载更多，不显示

### ISSUE THREAD

**Issue by sheisai** [XRecyclerView/XRecyclerView#314]
vivo x20 不能加载更多，不显示

**Comment by loveRose** [comment]
是无法上拉还是能上拉但是底部没有显示文字之类的

**Comment by fancinest** [comment]
vivo x20和x21都无法上拉加载更多，直接都不会调用onloading方法，不是不显示文字和没到底部

**Comment by YiChaoLove** [comment]
与https://github.com/XRecyclerView/XRecyclerView/issues/327 应该是一个问题

**Comment by af913337456** [comment]
@sheisai 是否使用了 CoordinatorLayout ？是的话，解决方法见 327 issue
