### ISSUE TITLE
fragment嵌套fragment(实现页面2级联动)中，出现严重的内存泄漏

### ISSUE THREAD

**Issue by renyuan1991** [XRecyclerView/XRecyclerView#321]
通过AndroidStudio的内存分析工具发现com.jcodecraeer.xrecyclerview.progressindicator.AVLoadingIndicatorView@320721408 (0x131dd200)
和com.jcodecraeer.xrecyclerview.SimpleViewSwitcher@326608896 (0x1377a800)中有未释放的mContext，导致activity无法销毁造成内存泄漏

**Comment by af913337456** [comment]
见 1.5.5 版本，已经修复
