### ISSUE TITLE
CoordinatorLayout那个Activity，滑动到底部的时候不会马上加载更多，过一会才会加载

### ISSUE THREAD

**Issue by 1280103995** [XRecyclerView/XRecyclerView#327]

**Comment by 2639949627** [comment]
我的RecyclerView版本是26.1.0，难道是最新版造成的？

**Comment by yangpin** [comment]
确实是版本的缘故，24.2没有问题 高版本的design和recyclerView 就有问题了 。
应该说 xRecycerView 还没有兼容高版本的滑动处理

**Comment by yangpin** [comment]
@1280103995 老铁你最终是怎么解决这个问题的？

**Comment by 1280103995** [comment]
@yangpin 我是重写滚动监听方法解决的，去掉滚动停止状态判断，然后在加载更多方法完成后调用RecyclerView的停止滚动方法。不过我没有用这个库，具体的你自己去试试吧。

**Comment by yangpin** [comment]
@1280103995 如果不用这个库 也就没有问题了，我也决定自己写一个加载更多逻辑，谢谢你的意见！

**Comment by yangpin** [comment]
@1280103995 我最终还发现了卡顿的原因 在RecyclerView的 ViewFlinger源码中 第4932行代码 关于是否有关联滑动的父布局那里的判断有关 我们加载更多的逻辑和它这个状态有矛盾，加载更多的时候这个地方就会产生卡顿。
解决方法是在XrecyclerView里面重载hasNestedScrollingParent 方法，直接返回false，这样滑动就很流畅了。

**Comment by 1280103995** [comment]
@yangpin 我刚试了下重写hasNestedScrollingParent 方法，直接返回false，问题依旧，版本26.1.0。不知道你是怎么改的

**Comment by wangshanhai** [comment]
我也遇到同样的问题。版本27.1.1滑动到底部基本都延迟1.5秒才会加载

**Comment by wangshanhai** [comment]
@yangpin 我也试了下重写hasNestedScrollingParent 方法，直接返回false，问题依旧，版本27.1.1，也是没什么效果

**Comment by 1280103995** [comment]
@wangshanhai 把onScrollStateChanged（应该叫这个名字吧）里的逻辑剪切到onScrolled中，并且把if条件的滚动停止才加载的条件去掉，加载完后stopScroll();

**Comment by Roger110** [comment]
我这里也有这个问题，把CollapsingToolbarLayout的收缩打开后就有

**Comment by YiChaoLove** [comment]
貌似这是RecyclerView的一个bug : https://issuetracker.google.com/issues/66996774

**Comment by YuzurihaInori** [comment]
贴一个解决方法
`
public class FixAppBarLayoutBehavior extends AppBarLayout.Behavior {

    public FixAppBarLayoutBehavior() {
        super();
    }

    public FixAppBarLayoutBehavior(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    @Override
    public void onNestedScroll(CoordinatorLayout coordinatorLayout, AppBarLayout child, View target,
                               int dxConsumed, int dyConsumed, int dxUnconsumed, int dyUnconsumed, int type) {
        super.onNestedScroll(coordinatorLayout, child, target, dxConsumed, dyConsumed,
                dxUnconsumed, dyUnconsumed, type);
        stopNestedScrollIfNeeded(dyUnconsumed, child, target, type);
    }

    @Override
    public void onNestedPreScroll(CoordinatorLayout coordinatorLayout, AppBarLayout child,
                                  View target, int dx, int dy, int[] consumed, int type) {
        super.onNestedPreScroll(coordinatorLayout, child, target, dx, dy, consumed, type);
        stopNestedScrollIfNeeded(dy, child, target, type);
    }

    private void stopNestedScrollIfNeeded(int dy, AppBarLayout child, View target, int type) {
        if (type == ViewCompat.TYPE_NON_TOUCH) {
            final int currOffset = getTopAndBottomOffset();
            if ((dy < 0 && currOffset == 0)
                    || (dy > 0 && currOffset == -child.getTotalScrollRange())) {
                ViewCompat.stopNestedScroll(target, ViewCompat.TYPE_NON_TOUCH);
            }
        }
    }
}
`
将Behavior设置到AppBarLayout上，例如
` 
<android.support.design.widget.AppBarLayout
        android:id="@+id/appbar_layout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:layout_behavior="com.xx.xx.FixAppBarLayoutBehavior"
        android:fitsSystemWindows="true">
`

**Comment by wslaimin** [comment]
> 贴一个解决方法
> `
> public class FixAppBarLayoutBehavior extends AppBarLayout.Behavior {
> 
> ```
> public FixAppBarLayoutBehavior() {
>     super();
> }
> 
> public FixAppBarLayoutBehavior(Context context, AttributeSet attrs) {
>     super(context, attrs);
> }
> 
> @Override
> public void onNestedScroll(CoordinatorLayout coordinatorLayout, AppBarLayout child, View target,
>                            int dxConsumed, int dyConsumed, int dxUnconsumed, int dyUnconsumed, int type) {
>     super.onNestedScroll(coordinatorLayout, child, target, dxConsumed, dyConsumed,
>             dxUnconsumed, dyUnconsumed, type);
>     stopNestedScrollIfNeeded(dyUnconsumed, child, target, type);
> }
> 
> @Override
> public void onNestedPreScroll(CoordinatorLayout coordinatorLayout, AppBarLayout child,
>                               View target, int dx, int dy, int[] consumed, int type) {
>     super.onNestedPreScroll(coordinatorLayout, child, target, dx, dy, consumed, type);
>     stopNestedScrollIfNeeded(dy, child, target, type);
> }
> 
> private void stopNestedScrollIfNeeded(int dy, AppBarLayout child, View target, int type) {
>     if (type == ViewCompat.TYPE_NON_TOUCH) {
>         final int currOffset = getTopAndBottomOffset();
>         if ((dy < 0 && currOffset == 0)
>                 || (dy > 0 && currOffset == -child.getTotalScrollRange())) {
>             ViewCompat.stopNestedScroll(target, ViewCompat.TYPE_NON_TOUCH);
>         }
>     }
> }
> ```
> }
> `将Behavior设置到AppBarLayout上，例如`
> <android.support.design.widget.AppBarLayout
> android:id="@+id/appbar_layout"
> android:layout_width="match_parent"
> android:layout_height="wrap_content"
> app:layout_behavior="com.xx.xx.FixAppBarLayoutBehavior"
> android:fitsSystemWindows="true">
> `

解决了我的问题，请问是什么原因？

**Comment by t894924815** [comment]
> 贴一个解决方法
> `
> public class FixAppBarLayoutBehavior extends AppBarLayout.Behavior {
> 
> ```
> public FixAppBarLayoutBehavior() {
>     super();
> }
> 
> public FixAppBarLayoutBehavior(Context context, AttributeSet attrs) {
>     super(context, attrs);
> }
> 
> @Override
> public void onNestedScroll(CoordinatorLayout coordinatorLayout, AppBarLayout child, View target,
>                            int dxConsumed, int dyConsumed, int dxUnconsumed, int dyUnconsumed, int type) {
>     super.onNestedScroll(coordinatorLayout, child, target, dxConsumed, dyConsumed,
>             dxUnconsumed, dyUnconsumed, type);
>     stopNestedScrollIfNeeded(dyUnconsumed, child, target, type);
> }
> 
> @Override
> public void onNestedPreScroll(CoordinatorLayout coordinatorLayout, AppBarLayout child,
>                               View target, int dx, int dy, int[] consumed, int type) {
>     super.onNestedPreScroll(coordinatorLayout, child, target, dx, dy, consumed, type);
>     stopNestedScrollIfNeeded(dy, child, target, type);
> }
> 
> private void stopNestedScrollIfNeeded(int dy, AppBarLayout child, View target, int type) {
>     if (type == ViewCompat.TYPE_NON_TOUCH) {
>         final int currOffset = getTopAndBottomOffset();
>         if ((dy < 0 && currOffset == 0)
>                 || (dy > 0 && currOffset == -child.getTotalScrollRange())) {
>             ViewCompat.stopNestedScroll(target, ViewCompat.TYPE_NON_TOUCH);
>         }
>     }
> }
> ```
> }
> `将Behavior设置到AppBarLayout上，例如`
> <android.support.design.widget.AppBarLayout
> android:id="@+id/appbar_layout"
> android:layout_width="match_parent"
> android:layout_height="wrap_content"
> app:layout_behavior="com.xx.xx.FixAppBarLayoutBehavior"
> android:fitsSystemWindows="true">
> `

666，完美解决
