### ISSUE TITLE
How to show Header if list size is zero...

### ISSUE THREAD

**Issue by ashishCDN0135** [XRecyclerView/XRecyclerView#332]
Facing issue that my header is not visible when my list size is zero..

**Comment by af913337456** [comment]
you can see the demo of LinearActivity , when list size is zero m the header still visible

**Comment by ashishCDN0135** [comment]
@af913337456 ....thanks for your feedback...in my case it is not showing because i not used layoutmanager,after using that it shows header.u can close this issue.

**Comment by af913337456** [comment]
thanks for using xr
