### ISSUE TITLE
XRecyclerView上拉加载更多一直回调onCreateViewHolder()

### ISSUE THREAD

**Issue by rwz657026189** [XRecyclerView/XRecyclerView#334]
如题，当我一次加载100条数据，在这100条数据中onCreateViewHolder（）只会调用固定次数。但我加载下一页100条时，onCreateViewHolder（）仍然会调用... 这样一直加载下一页，会一直调用onCreateViewHolder导致ViewHolder越来越多，内存消耗越多。实际情况每页加载20条，这种情况更严重。跟XRecyclerView有关系吗？

**Comment by af913337456** [comment]
没关系，检查自己的代码逻辑
