### ISSUE TITLE
recyclerview没有占满屏幕就不会触发上拉加载更多

### ISSUE THREAD

**Issue by diao-jian** [XRecyclerView/XRecyclerView#340]
比如我一个网络请求要请求10跳数据，首次请求对应10个item,但每个item的高度都偏低，10个item的总高度并没有占满屏幕，这时候无论如何也触发不了上拉加载更多，而我的数据不止10条，还有很多条需要上拉加载出来

**Comment by youlookwhat** [comment]
```java  public void onScrollStateChanged(int state) {} ```内取消```java layoutManager.getItemCount() > layoutManager.getChildCount()```这个判断条件试试
