### ISSUE TITLE
getHeadersCount()报空这个问题怎么解决？？

### ISSUE THREAD

**Issue by JamChanGitHub** [XRecyclerView/XRecyclerView#343]
java.lang.NullPointerException: Attempt to invoke virtual method 'int com.jcodecraeer.xrecyclerview.XRecyclerView$WrapAdapter.getHeadersCount()

**Comment by af913337456** [comment]
新版本已经解决了的

**Comment by fukemy** [comment]
still get problem when adapter empty -> refresh -> null -> CRASH
