### ISSUE TITLE
引入后用不了

### ISSUE THREAD

**Issue by chen-krolser** [XRecyclerView/XRecyclerView#345]
引入后控件用不了 布局文件报错
![default](https://user-images.githubusercontent.com/24190317/38975706-6a2fb682-43e1-11e8-9ca7-1019a18293e9.png)
点击XRecyclerview也是可以跳转关联的不知道是什么原因 有谁遇到过吗

**Comment by af913337456** [comment]
考虑下文件冲突。一般和 sdk 或其它库相关。
