### ISSUE TITLE
LinearStickyScrollActivity 无效果

### ISSUE THREAD

**Issue by HmLifengfeng** [XRecyclerView/XRecyclerView#374]
LinearStickyScrollActivity  这个类不能用了? 没实现效果呢。topview 被划上去之后，就再也划不出来了

**Comment by samuelhehe** [comment]
me toooo ，

**Comment by samuelhehe** [comment]
StickyScrollLinearLayout     setTargetFirstVisiblePosition(0);    i'm work fine, tks

**Comment by af913337456** [comment]
参考 demo activity 使用。因为没出现过你说的这个情况
