### ISSUE TITLE
怎么添加footer？

### ISSUE THREAD

**Issue by 86userused** [XRecyclerView/XRecyclerView#383]

**Comment by 86userused** [comment]
mRecyclerView.setFootView(footer,new CustomFooterViewCallBack() {
            @Override
            public void onLoadingMore(View yourFooterView) {
                Toast.makeText(LinearActivity.this, "onLoadingMore", Toast.LENGTH_SHORT).show();

            }

            @Override
            public void onLoadMoreComplete(View yourFooterView) {
                Toast.makeText(LinearActivity.this, "onLoadMoreComplete", Toast.LENGTH_SHORT).show();

            }

            @Override
            public void onSetNoMore(View yourFooterView, boolean noMore) {
                Toast.makeText(LinearActivity.this, "onSetNoMore", Toast.LENGTH_SHORT).show();
            }
        });
好像不是这样添加的，能不能贴下代码？谢谢了

**Comment by TYUpya** [comment]
目前没有这个功能哦

**Comment by af913337456** [comment]
这个是设置自定义 footer view
