### ISSUE TITLE
XRecyclerView添加 头部，该头部包含一个recyclerView出现滑动冲突。

### ISSUE THREAD

**Issue by adustdu2015** [XRecyclerView/XRecyclerView#390]
XRecyclerView添加 headerView，该headerView包含一个recyclerView出现滑动冲突。
参考了一下网上的设置  headerView 中的 recyclerView.setFocusable(false).第一次可以使用。
但是 我利用ViewPager再滑动回来的时候就冲突啦。

**Comment by af913337456** [comment]
@adustdu2015 say something
