### ISSUE TITLE
com.jcodecraeer:xrecyclerview:1.5.9 获取不到

### ISSUE THREAD

**Issue by petterEat** [XRecyclerView/XRecyclerView#393]
com.jcodecraeer:xrecyclerview:1.5.9 获取不到

**Comment by petterEat** [comment]
com.jcodecraeer:xrecyclerview:1.5.8 可以获取到

**Comment by af913337456** [comment]
建议检查下网络原因，我新建一个项目获取，依然是可以的。
![image](https://user-images.githubusercontent.com/10436277/59661180-d1311c00-91dc-11e9-954b-344e87ee1084.png)
