### ISSUE TITLE
出现内存泄漏，在ArrowRefreshHeader->AVLoadingIndicatorView(context)

### ISSUE THREAD

**Issue by qindachang** [XRecyclerView/XRecyclerView#56]
class ArrowRefreshHeader--->AVLoadingIndicatorView progressView = new AVLoadingIndicatorView(this.getContext());
这里的context持有产生内存泄漏。

**Comment by qindachang** [comment]
作者你很棒！鼓励一下！
不好意思啊 ， 你对你的代码修改了一部分，因为产生内存泄漏没办法。
查了AVLoadingIndicator这个库，发现修改以来也非常简单。
`
public void setProgressStyle(int style) {
        if(style == ProgressStyle.SysProgress){
            mProgressBar.setView(new ProgressBar(mContext, null, android.R.attr.progressBarStyle));
        }else{
            progressView = new AVLoadingIndicatorView(this.getContext());
            progressView.setIndicatorColor(0xffB5B5B5);
            progressView.setIndicatorId(style);
            mProgressBar.setView(progressView);
        }
    }
`

`
public void setState(int state) {
		if (state == mState) return ;

		if (state == STATE_REFRESHING) {	// 显示进度
			mArrowImageView.clearAnimation();
			mArrowImageView.setVisibility(View.INVISIBLE);
            progressView.setVisibility(VISIBLE);
			mProgressBar.setVisibility(View.VISIBLE);
		} else if(state == STATE_DONE) {
            mArrowImageView.setVisibility(View.INVISIBLE);
            progressView.setVisibility(GONE);
            mProgressBar.setVisibility(View.INVISIBLE);
        } else {	// 显示箭头图片
			mArrowImageView.setVisibility(View.VISIBLE);
			mProgressBar.setVisibility(View.INVISIBLE);
		}
`

**Comment by pengdun** [comment]
加载的数据位置出现错误,你们是怎么解决的呢?

**Comment by qindachang** [comment]
我目前还没有遇到这个问题，如果数据位置不对，我建议你用序列化类再尝试一下看看

**Comment by l123456789jy** [comment]
@pengdun   在viewholder中设置 setIsRecyclable(false);

**Comment by pengdun** [comment]
@l123456789jy 已解决,虽然不是按照你的方法,还是感谢.

**Comment by 252830311** [comment]
@qindachang 我也遇到了这个问题,没有看明白怎么解决的

**Comment by MichaelMeng666** [comment]
@qindachang 你的修改方案是在整个ArrowRefreshHeader类里，将AVLoadingIndicatorView progressView设置为全局属性吗，所有类里用到的都用一个？

**Comment by TOPWARNING** [comment]
这样可以解决
![image](https://cloud.githubusercontent.com/assets/6268829/23539253/f68f8fd8-0014-11e7-8810-d6437e3333bf.png)

**Comment by jan27th** [comment]
@TOPWARNING setTarget()方法传什么？

**Comment by af913337456** [comment]
@qindachang @pengdun @l123456789jy @MichaelMeng666 @252830311 见 1.5.5 版本，已经修复
