### ISSUE TITLE
How to remove header ?

### ISSUE THREAD

**Issue by derohimat** [XRecyclerView/XRecyclerView#62]
i had to add header before set adapter into recyclerView, but after i call request header no data found. And i want to remove that header, is possible now ?

**Comment by jianghejie** [comment]
“but after i call request header no data found”，what does this mean？

**Comment by cjkiss** [comment]
就是 能不能添加一个去掉head 的功能 ，我用这个XRecyclerView删除item 报错java.lang.IllegalArgumentException: Called attach on a child which is not detached: ViewHolder{35079d1 position=0 id=-1, oldPos=-1, pLpos:-1 not recyclable(1)}

**Comment by pengdun** [comment]
在刷新时不要做remove动作

**Comment by cjkiss** [comment]
public void removeItem(int position) {
        this.mDatas.remove(position);
        this.notifyItemRemoved(position);
    }
我没有刷新 只是先remove然后更新数据

**Comment by derohimat** [comment]
“but after i call request header no data found”，what does this mean？

oo sorry, i mean no data for header from API. so i must remove header, because no data for header.
but i already addHeader before it.

**Comment by derohimat** [comment]
@cjkiss 
public void removeItem(int position) {
this.mDatas.remove(position);
this.notifyItemRemoved(position);
}

i ever try it, but error

**Comment by pengdun** [comment]
public void clear() {
        if (list != null && list.size() > 0) {
            int size = list.size();
            list.clear();
            notifyItemRangeRemoved(1, size);
        }
    }

**Comment by af913337456** [comment]
it has been fixed , see the commits , 2017-11-14
