### ISSUE TITLE
Called attach on a child which is not detached 异常

### ISSUE THREAD

**Issue by hehonghui** [XRecyclerView/XRecyclerView#69]
29486-29486/com.newsdog E/AndroidRuntime: java.lang.IllegalArgumentException: Called attach on a child which is not detached: ViewHolder{3df7ff53 position=0 id=-1, oldPos=-1, pLpos:-1}
05-04 12:19:30.648 29486-29486/com.newsdog E/AndroidRuntime:     at android.support.v7.widget.RecyclerView$4.attachViewToParent(RecyclerView.java:587)
05-04 12:19:30.648 29486-29486/com.newsdog E/AndroidRuntime:     at android.support.v7.widget.ChildHelper.attachViewToParent(ChildHelper.java:239)
05-04 12:19:30.648 29486-29486/com.newsdog E/AndroidRuntime:     at android.support.v7.widget.RecyclerView.addAnimatingView(RecyclerView.java:1030)
05-04 12:19:30.648 29486-29486/com.newsdog E/AndroidRuntime:     at android.support.v7.widget.RecyclerView.animateChange(RecyclerView.java:3117)

**Comment by hehonghui** [comment]
相关说明 : https://code.google.com/p/android/issues/detail?id=172636

**Comment by af913337456** [comment]
已修复，见最近的 commit ，2017-11-14
