### ISSUE TITLE
将下拉刷新 和上拉加载禁掉 会导致EmptyView显示不出来

### ISSUE THREAD

**Issue by chen2174471** [XRecyclerView/XRecyclerView#70]
mRecyclerView.setLoadingMoreEnabled(false);
  mRecyclerView.setPullRefreshEnabled(false);
  mRecyclerView.setEmptyView(mEmptyView);
将下拉刷新 和上啦加载禁掉 会导致EmptyView显示不出来 。看了源码 觉得应该不会出现这个问题，但确实是有。

**Comment by Damonzh** [comment]
你不禁用下拉刷新或者上拉加载的话，emptyView能显示出来？我怎么都显示不出来

**Comment by chen2174471** [comment]
可以，首先你的emptyview需要在layout中，然后设置给xRecyclerView。数据集为空的话 setAapter后就可以显示emptyview。 后来发现禁用放在setAdapter之后就可以了。

**Comment by Damonzh** [comment]
嗷 我把emptyview作为一个独立的布局了 可能是这个原因吧

2016年5月12日星期四，chen2174471 <notifications@github.com> 写道：

**Comment by UseLived** [comment]
为什么我都下拉和上拉都禁用不了呢？
``
<com.jcodecraeer.xrecyclerview.XRecyclerView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:id="@+id/recycler_view"/>
``

**Comment by liuyanji** [comment]
//        mRecyclerView.setPullRefreshEnabled(false);//禁止下拉刷新
//        mRecyclerView.setLoadingMoreEnabled();//禁止加载更多

**Comment by UseLived** [comment]
3Q
但是我代码里就是这样写的，放在setAdaper前后都不行。。

**Comment by itzuo** [comment]
请问setEmptyView怎么用啊？为啥我写了一个空页面也不会显示出来
